/**
 * Nomes brasileiros e o sexo que eles indicam — tirados do NOSSO CRM, não de lista genérica.
 *
 * Construída em 26/09/2026 a partir de 3.387 leads que tinham nome e sexo preenchidos nas
 * 19 contas. Por isso ela acerta os nomes do Norte e Nordeste que uma lista de internet
 * erraria — Raimundo, Francisca, Valderlene aparecem aqui porque aparecem nas clínicas.
 *
 * Só entrou nome com 80% ou mais de concordância entre os exemplos. Os votos minoritários
 * (`lucia` com 2 masculinos, `juliana` com 1) são erro no dado atual, não dúvida real —
 * medida assim, a captura de sexo que existe hoje erra 1 a 2%.
 *
 * Validação com teste cego (lista feita com metade dos exemplos, testada na outra metade):
 * 55% de cobertura, 97,0% de precisão. Com a lista completa a cobertura sobe.
 *
 * Para regerar: `backend/src/scripts/nomes-sexo.mjs` (lê o Kommo e reconstrói).
 */

/** Nomes femininos, um por linha de texto, separados por espaço. */
const FEMININOS = [
  "abadia adaiza adelita adelma adinair adir adriana adriele adrielly agda alana alcione alda",
  "aldeireis aldivamiranda ale alessandra alexandra alexandrina alexsandra alice aline",
  "almerinda alzira amanda ana anair analeia analina andrea andreana andreia andressa andreza",
  "ane anesia angel angela angelita aninha anita antonia aparecida ariadne ariana arianny",
  "arielly arimateia arine arlete ary atelia audicleia audineide aurea aurelice aurileia",
  "aurineide auxiliadora ayud barbara beatriz bel bellard benabet benedita berivane betania",
  "bete beth betty bia bianca bonfim brasilina brenda bruh bruna cacilda camila carla carlene",
  "carme carmem carmen carmiacy carol carolina caroline cassia casula catia cavalcante cecilia",
  "ceila celia celina celma cesara cezina cibelle cicera ciciana cida cidinha cintia cirlene",
  "claudene claudete claudia claudiana claudina claudineia clecia cleide cleidiane clemilda",
  "cleo cleonice cleria clesia cleude cleudilene cleusa cleuza clotilde coraci costa creusa",
  "creuza cris crislaine cristiana cristiane cristina crystielly daevely dafyny daiana daiane",
  "daika dailine dalva dalvina dalvirene dani daniela daniele daniella dany danyella darielma",
  "darlene day dayse debora deborah deise dejanir dejany delane delbra denia denilda denilde",
  "deurilene deusa deusanira deuzeli deuzimar devanil deycivan dheiny dhully diana dijanne dila",
  "dilma dinalva dineia dirce divani divia divina domingas dona dora doralice dorcilene",
  "dorilene dorinha dorvalina doxa drica dulce dulciane dulcy eberte eda ediene edilena edilene",
  "edilenemauricio edileny edileusa edileuza edilucia edimonica edina edinete edineuma edineusa",
  "edivania edlange edleuma edleuza edmara edna ednalva edneia eduarda efigenia eilanne elaine",
  "elcilene elda elena eleni elenice eleusa eli eliana eliane eliangela eliene eliete eliezer",
  "elisabete elisabetta elisama elisamia elisandra elisangela elisete elisolange elita elivania",
  "eliza elizabete elizabeth elizangela elizete elizeth elza elzir emely emilly enedina enir",
  "enivanda enolia ercilia erica erika erilnada eroisa eronildes erzi esmeraldina esmerinda",
  "esteiler estevania esther etiene euberth eudilane eugenia euina euza euzileni eva evaneide",
  "evanete evanilde evanir evilane evinha evoneide fabiana fabiola fabiula fabricia face fany",
  "fatima fernanda fher flavia flora floraci francidalva franciene francilene francinalva",
  "francineide francinete francisca furtunata gabriela gabryela gal gardenia geane geisa gene",
  "genecy geni genice genilda genilsa geovanna gerleane germana gesiane geusa geuzai gianna",
  "gildiene gilmara gilvan gilvana gilvania giorgia girlaine girlane giselda gisele gislane",
  "gislayne gizelia glaucia gleide gloria gorete graca graciane gracileni gracinha grasiele",
  "grazyele guacirene guadalupi guiomar heitor helaine helba helena helenice heleninha helenita",
  "heleuza hellem hellena helly heloisa hemilly hermelinda herondina hilda hildene homazia",
  "hortensia hulda humberto idalia idalina idy ilcirene ilda ildete ilma ilza inacia iolanda",
  "iolete ione iracema iraci iracy irailde irany iris irismar isa isabel isaneide isanete",
  "isaura ivanda ivanete ivanilde ivannyra ivete ivone ivonete iza izabel izaura izenilde",
  "izequiel izolda izordina jacenilra jaci jaciara jacinta jacira jacirene jainara jaira jaires",
  "jan janaina jane janete janice januaria jaqueline jardeane jarlucia jaysa jeane jeany",
  "jennifer jerononima jerusaucamedeiros jessiane jessica jhony jhullya joaci joana joanita",
  "jocelia jocicley joella joice joicy jorcelina jordana jordane jordaninha joseane josefa",
  "joselia joselita josian josiane josilene josineide josy josyaane jozefa ju jucenir juh julia",
  "juliana juliane julieta jura juracy jurema jusileide jussara juvank kailan kaline kalita",
  "kamila kamyla karina karine kariny karitta karla karlla karol karollainy kassandra kassia",
  "katheleen katia katiana katiucia kayra keila keilla kel kelly kelma kelvia kenia kesia",
  "keytna keytty kiara lady laiane laide laina lais lara larissa laryssa lauedany laura",
  "laurenice lauro lays lazara lea leda ledna leia leide leidi leidiane leidianne leidinalva",
  "leidinayra leila leiliana leiliane len lenice lenita lenny leocina leolina leonice leonisia",
  "leonora leticia leya leyllane lhindalya lidia lidiane ligia lili lilian liliane lina",
  "lindalva lindauva lindinaura lira livia lizena lolania lora loraine lorena lorrana lourdes",
  "lourena lourivaldo lu luana luane lubia lucelia lucemar luci lucia luciana luciara luciene",
  "lucileia lucilene lucimar lucimaria lucineide lucinete ludymilla luisa luiza luna lurdes",
  "lusia lusiflan lusinete luz luzanira luzenira luzia luzinete luzinilia lygia madalena maeli",
  "magda magnolia maia maiane maira malu manuelle mara marcela marcele marcelina marcelle",
  "marcia marcielene marcilene margarete margarida mari maria mariana mariangela mariani marie",
  "mariene marieusa marilda marileia marileide marilene marilia marilourd marilza marina",
  "marinalva marineide marinete marisa maristela marivalda marla marlei marleide marlene",
  "marlete marli marliene marliete marlu marluce marly marney marta mary marya maura mayane",
  "mayara maylla meigna meire meires meirivany melissa mercia mezenes michela michele micheli",
  "micherle miih mika mila milena milene milly mira miriam mirrada monica morena mozania mto",
  "mychelly nadia nadir naiara nailma nair naira nalva nana nanci narlla natalia natalina",
  "nathacha nathy natielly nayara naylla naza nazare nedi nediana neia neide nelcima neli",
  "nelita nena nene nere neuder neura neusa neuta neuzelina neydilene nice nicolly nida nilce",
  "nilda nilde nilsa nilva nilza nira nivaldo noeme noemi noemia nonata nora nubia nvoip odete",
  "olegaria oliveira olivia oneide oneidy orialle oriana ottonelson ozerina pamela paola",
  "patricia paula pedra perpetua poliana polliana polyana pra preta priscila priscilla queiza",
  "quiteria rafaela railda railma raimunda raimundinha rana raquel rayane rayka raylla re",
  "rebeca regiane regiani regilma regina regy rejane renata renilda renivan reuly riquele rita",
  "ritinha ro roberta robsleya rogneia romilda ronilda rosa rosala rosalia rosalina rosana",
  "rosangela rose roseclea roseilane roselaine roseli roselia rosely rosemara rosemeire",
  "rosicleide rosilda rosilene rosimeire rosinalva rosivalda rosy rozelia rozimaria rozineide",
  "rozivania rubenita ruth salete samia samira sandra santana sara sarah selma selmi sena",
  "sheila shirlene si sidneia silene silma silva silvana silvane silvaneide silvania silvia",
  "simone simonia sioni sirlaine sirlene socorro sol solange solenice sonia soraia sousa suane",
  "sue suelane suelen suelene sueli suelia suely suleny sumie sunamita susana suzana suzane",
  "suzanne suzi suzyane syrlei tais talita tami tammy tania tassia tatiana tatiane taty tatyane",
  "tel telma tercilia teresa teresinha tereza terezinha tevane thainna thais thallyta thalya",
  "thamara thaty thawanny thayane thays tuanny udinezia uiara urcula val valdenice valdete",
  "valdicleia valdineia valdira valdirene valeria valquiria vanda vandejane vanderlan",
  "vanderleia vaneci vanessa vaneza vania vaniaa vanice vanilda vanilza vanusa vanusia vanya",
  "vera verinha veronica vilane vilda vilma virginia vitoria vivi vpaula wadila wal walkyria",
  "walter wanda wanessa wilma yasmin yndrid yona za zaira zara zaza zelia zelma zenia zenilda",
  "zete zilanda zilda zilma zima zumira",
].join(" ").split(" ");

/** Nomes masculinos. */
const MASCULINOS = [
  "abdiel abell abiel abilio adailton adalberto adalto adao adauto adelia adelmo ademar",
  "ademilson adenair adevaldo adilson adjair admilton adonias adriano agamilo ageu agnaldo",
  "ailton alain alan albert alberto aldaires aldo alesandro alex alexandre alexandrelim",
  "alexsandro ali alicio alisson allan allanlablancaruiz almir alvamiro amaral amarildo",
  "amazilio ambrosio amilton amparo ananias anderson andre andrei anex anselmo antonio antony",
  "areolino ariel arinaldo arlan arlindo armarinho arnaldo arquiminio arthur assuncao audinete",
  "augusto aurino baemadenilson benedito benilson bento bil boskinho brayon brito brunao bruno",
  "bryan calisto carimbo carleandro carlindo carlinho carlito carlos carlozan carvalho cassiano",
  "cassio celio celso cesar chagas charles chico cicero ciro civaldo claudemar claudemir",
  "claudiane claudiano claudinei claudio cleber clebson cleibes cleidiomar cleilson cleirton",
  "cleiton cleomisom cleonildo cleudinaldo cleusimar cley cleyton coelho cristiano dalcimar",
  "dalmir daniel danillo danilo dario davi david davidnek deivison delirio dellatorre delson",
  "deniel denilson denir denis deodato dercino deusivan devalci diego dilson dimas diniz diogo",
  "dione dirceu dito divino djalma domingo domingos dorival doutor drika dudu edcarlos eden",
  "edenilson eder edgar edicassio edieynes edilom edilson edimilson edinaldo edivaldo",
  "edivanildo edmilson edmundo edner edson eduardo edvaldo eisler elano elenilde elenilson",
  "eleonardo elinaldo elio eliomar elismar elissandro elizeu eloi emerson enio enos enzo",
  "erenaldo eri erick erinaldo erinece eriton erivaldo eromar esdras esteylon ethan euclides",
  "euricobezerradasilva eusinete evandro evane evanilson everaldo ezequiel fabio fabliciano",
  "fabricio fagner fanoel fausto felipe felizardo fernando filomeno flanzio flavio foncionario",
  "fracimar fracinildo francinaldo francisco francivaldo frank franquilino fyama gabriel",
  "galdino ge geilson gelson genildo genilson genilton geolandia geolmar geovana geovane",
  "gerlando gerlisson gerson gesmar gesse gessica getulio gilberto gildevane gildo gilmar",
  "gilsom gilsomar gilson gilvani giovani gisel glaudenia gmail grafica guga guidacy guilherme",
  "gustavo hamilton henrique hercules herllon higo hilton honorio hugo iamane icaro idelfonso",
  "igor ildimar ilton inaldo iranilto irderlan isaias isaquiel ismael israel itamar ivadelson",
  "ivan ivanaldo jack jacksuel jacson jademir jadson jaime jaimes jair jamilson jandes janes",
  "janiclesio janildo janilson janio jardel jarlan jason jean jeferson jefferson jhon jhonata",
  "jionatan jn joabson joaldo joao joaquim jobson jocelino joel joelsom joelson johnny",
  "jorcivaldo jordson jorge jorgevan jorginho jose joselino joselio josemy josevaldo josimar",
  "jositon josivan josue juberto jucelino jucivan juliano julio junielson junior juscelino",
  "juvenal kassio kauan kelson kenedy keney kennedy keyla khalil klauber kleber kleyton kris",
  "leandro ledimar lemos leo leonardo leonidas leonildo levi levy liberto lide lindomar loro",
  "luan lucas lucenilda luciano lucicleiton lucindo lucio lucival lucivaldo lucivando luis luiz",
  "luizinho madson magno maic maicon mamedio manoel marcelino marcelo marcinho marcio marco",
  "marcos marcus mardem mardonio mariinha marinho mario marivaldo marks marlone martins",
  "martonio mateus matheus mauricelio mauricio maurilio mauro max maycon mazes me mega michael",
  "miguel milton minervino miqueias moacir moisaniel moises naison nalberto naldo nando",
  "natanael nelson nerismar neude neuza neves ney nezito nicanor nilcimar nilson nilton nonato",
  "odair odias oemerson orlanderson osires osmar osmir osvaldo otavio otto ozaias oziel pacheco",
  "pascoal paulinho paulo pede pedro pericles petronio pinheiro plinio rafa rafael rafhael rai",
  "raifran railson raimundo ramon ramos rangel raniere raylan reginaldo regis regivaldo",
  "reinaldo renato renilson rennan resiliencia ribeiro riberto ricardo richel rick rivaldo",
  "roberley robert roberto rodrigo rodrigues rogerio romao romario romero romeu romildo romulo",
  "ronaldo ronei ronilson rosar rosembeg rosiane rubens rui ruti ryan sabor salvatoojose",
  "sanches sandreano sandro santos saullo saulo scotty sebastiao sergio sidney silas silder",
  "silvano simonebrito sirdeley talisvan tallis tavares telmo thaison thales tharcyo thelma",
  "theo thiago tiago vagno valcir valdeci valdecir valdemar valdemir valdino valdir valdivino",
  "valmir valteni valter valtercio vandeilson vando vere veridiano victor vilmondes virgilio",
  "viviane wadson wagner walber waldemir waldir waldriano walisson wallisson wallyson wander",
  "wanderley wanderson washington wedson welber welder welithon wellington wellyngton welton",
  "wendell weryk wesley weslley wildes will willas william williamys willian wilson wladimir",
  "wladir wmf xavier ygor ze zeca zelson zeze zezim zico zildo",
].join(" ").split(" ");

export const NOMES: ReadonlyMap<string, "Feminino" | "Masculino"> = new Map([
  ...FEMININOS.map((n) => [n, "Feminino"] as const),
  ...MASCULINOS.map((n) => [n, "Masculino"] as const),
]);
